### ISSUE TITLE
关于该项目的一些疑问

### ISSUE THREAD

**Issue by ddawx123** [zsxsoft/blog.zsxsoft.com#1]
关于该主题开源项目，想问一下如何使用的？是不是你博客的ajax主题？

**Comment by zsxsoft** [comment]
是，但它不可能直接拿给Z-BlogPHP用，因为它本来就不是一个ZBP的主题。
你需要配合以下部件使用：
 - Z-BlogPHP作为后端
 - （真正的主题）JSON主题
![image](https://cloud.githubusercontent.com/assets/2398785/23054455/f9f52656-f51a-11e6-815f-bc73b2a9be0c.png)
 - 后端路由插件
![image](https://cloud.githubusercontent.com/assets/2398785/23054471/09a369c8-f51b-11e6-97ca-e2490c0a929b.png)
- 后端控制权转移脚本


由于其内含太多私货，不可能开源，就算开源配置也麻烦，还存在其它问题，所以不能直接使用。
所以主题仅能作为参考。
