### ISSUE TITLE
你好，请问有考虑把react、nextjs更新到最新版本吗

### ISSUE THREAD

**Issue by ghost** [zsxsoft/blog.zsxsoft.com#4]

**Comment by zsxsoft** [comment]
升级难度太高，不如重写。

**Comment by ghost** [comment]
@zsxsoft 

https://blog.zsxsoft.com/post/39

谢谢，看了你的文章，很棒
 我也想给我的网站实现， 整个网站走cdn（为了seo、首屏速度）

用户登录后，走csr， 减少请求，节省流量

感觉实现起来好难呀

**Comment by zsxsoft** [comment]
如文章所说，我这个项目并没有应用这篇文章使用到的技术。

**Comment by zsxsoft** [comment]
关于CSR的使用可参考文章中提到的GitHub。

**Comment by ghost** [comment]
谢谢
